In [3]:
import numpy as np
import pandas as pd

In [4]:
# initialize data of lists.
data = {'Name':['Vamshi','Sairam','Madhan','Rahul','Ashok','Ravi','Praveen'],
        'Age_Sex':['20_M', '21_M', '25_M', '30_M','45_M','32_M','200_M'],
        'height(cm)':[160,-175.5,140.7,0.0,np.NaN,162.4,165],
        'Weight(kg)':[80, 67, np.NaN, 62.5, 66.4, np.NaN, 73],
        'Spend_A':[2000,3000,5000,7000,np.NaN,-2000, np.NaN],
        'Spend_B':[200, 500, 1500, 1700, 2000, np.NaN,750],
        }
  
# Create DataFrame
df = pd.DataFrame(data)
  
# Print the output.
df

Name Age_Sex  height(cm)  Weight(kg)  Spend_A  Spend_B
0   Vamshi    20_M       160.0        80.0   2000.0    200.0
1   Sairam    21_M      -175.5        67.0   3000.0    500.0
2   Madhan    25_M       140.7         NaN   5000.0   1500.0
3    Rahul    30_M         0.0        62.5   7000.0   1700.0
4    Ashok    45_M         NaN        66.4      NaN   2000.0
5     Ravi    32_M       162.4         NaN  -2000.0      NaN
6  Praveen   200_M       165.0        73.0      NaN    750.0

*7. NumPy ndarray object
The most important object defined in NumPy is an N-dimensional array called ndarray. It describes the collection of items of the same type.

 The basic ndarray is created using an array function in NumPy with the following code snippet as follows:−

 

numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

The above constructor takes the following parameters:−

object - Any object exposing the array interface method returns an array, or any (nested) sequence.


dtype - Desired data type of array, optional


copy - (Optional) - By default (true), the object is copied


order - C (row major) or F (column major) or A (any) (default)


subok - By default, returned array forced to be a base class array. If true, sub-classes passed through


ndmin - Specifies minimum dimensions of resultant array**

In [5]:
# one dimensional array

a = np.array([1,2,3])

print(a)

[1 2 3]


In [6]:
a.shape

(3,)

In [7]:
df

Name Age_Sex  height(cm)  Weight(kg)  Spend_A  Spend_B
0   Vamshi    20_M       160.0        80.0   2000.0    200.0
1   Sairam    21_M      -175.5        67.0   3000.0    500.0
2   Madhan    25_M       140.7         NaN   5000.0   1500.0
3    Rahul    30_M         0.0        62.5   7000.0   1700.0
4    Ashok    45_M         NaN        66.4      NaN   2000.0
5     Ravi    32_M       162.4         NaN  -2000.0      NaN
6  Praveen   200_M       165.0        73.0      NaN    750.0

In [8]:
# one dimensional array
n1 = np.array(df[:1])
print(n1)

[['Vamshi' '20_M' 160.0 80.0 2000.0 200.0]]


In [9]:
n1.shape

(1, 6)

In [10]:
n1.ndim

2

*n2 = np.array(df[:2], dtype=int)**

In [11]:
# two dimensional array

b = np.array([[1, 2], [3, 4]])

print(b)
b.ndim

[[1 2]
 [3 4]]


2

In [12]:
b.shape

(2, 2)

In [13]:
# three dimensional array

c = np.array([[[1,2],[3,4],[5,6]]])

print(c)
c.ndim

[[[1 2]
  [3 4]
  [5 6]]]


3

In [14]:
c.shape

(1, 3, 2)

**dataset, a three dimensional array of the 


n3 = np.array(df[:3], dtype=int)**

In [15]:
# minimum dimensions is nothing but creating required no.of dimensions

d = np.array([1, 2, 3, 4, 5], ndmin = 3)

print(d)

[[[1 2 3 4 5]]]


*NumPy data types
NumPy supports a much greater variety of numerical data types than Python. The following table shows most common data types defined in NumPy.

bool_ - Boolean (True or False) stored as a byte


int_ - Default integer type (same as C long; normally either int64 or int32)


intc - Identical to C int (normally int32 or int64)


intp - Integer used for indexing (same as C ssize_t; normally either int32 or int64)


int8 - Byte (-128 to 127)


int16 - Integer (-32768 to 32767)


int32 - Integer (-2147483648 to 2147483647)


int64 - Integer (-9223372036854775808 to 9223372036854775807)


float_ - Shorthand for float64


float16 - Half precision float: sign bit, 5 bits exponent, 10 bits mantissa


float32 - Single precision float: sign bit, 8 bits exponent, 23 bits mantissa


float64 - Double precision float: sign bit, 11 bits exponent, 52 bits mantissa**

In [16]:
# using array-scalar type 
 
dt = np.dtype(np.int32)

print(dt)

int32


In [17]:
dt = np.dtype(np.int)

*NumPy array attributes
 various NumPy array attributes.
 
  The attributes are 
  
  ndarray.shape, 
  
  ndarray.size, 
  
  ndarray.ndim, 
  
  ndarray.itemsize,
  
  ndarray.dtype 
   
  ndarray.data.

ndarray.shape
This array attribute returns a tuple consisting of array dimensions. 


It can also be used to resize the array. For a matrix with n rows and m columns, shape will be (n,m). 


The length of the shape tuple is therefore the number of axes, ndim.**

In [18]:
x1 = np.array([[1,2,3],[4,5,6]]) 

print(x1.shape)
x1.ndim

(2, 3)


2

In [19]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
x1.shape

(2, 3)

In [21]:
# check the shape of the n1 array

print(n1.shape)

(1, 6)


In [22]:
# resizes the ndarray 

x2 = np.array([[1,2,3],[4,5,6]])

x2.shape = (3,2) 

print(x2) 

[[1 2]
 [3 4]
 [5 6]]


*ndarray.size


It returns the total number of elements of the array. This is equal to the product of the elements of shape.**

In [23]:
# print the size of the x1 array

print(x1.size)

6


**reshape function**

NumPy also provides a reshape function to resize an array**

In [29]:
x1 = np.array([[1,2,3],[4,5,6]])

x1_reshaped = x1.reshape(1,6)

print(x1_reshaped)

[[1 2 3 4 5 6]]


In [30]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

**ndarray.ndim**

This array attribute returns the number of axes (dimensions) of the array.**

In [31]:
# create an array of evenly spaced numbers 

import numpy as np
x3 = np.arange(24)

print(x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [32]:
# confirm that the above array is a one dimensional array 
import numpy as np

x3 = np.arange(24) 

print(x3.ndim) 

1


In [33]:
a = np.arange(12)

In [34]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
b = a.reshape(3,4)

In [36]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
# reshape the above array
# In the below example reshaping can be happend by 
# (3,4,2)  here 3 represents no.of matrices and 4,2 represents its size like 4*2=8,8,8=total of 24

x4 = x3.reshape(4,3,2) 

print(x4)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


*10. NumPy array creation
A new ndarray object can be constructed by any of the following array creation routines. There are several ways to create arrays. These are listed below:-

array function


empty function


zeros function


ones function


arange function


linspace function**

**array function**

In [39]:
# create an array 
    
x7 = np.array([2,3,4])

x7

array([2, 3, 4])

In [40]:
# check its dtype

x7.dtype

dtype('int64')

In [41]:
x8 = np.array([1.2, 3.5, 5.1])

x8.dtype

dtype('float64')

The function zeros creates an array full of zeros. By default, the dtype of the created array is float.

The following examples demonstrate the use of the zeros function:-**

In [42]:
# array of five zeros

x10 = np.zeros(5) 

print(x10)

[0. 0. 0. 0. 0.]


In [43]:
x11 = np.zeros((5,), dtype = np.int)

print(x11)

[0 0 0 0 0]


*ones function


The function ones creates an array full of ones. The default dtype is float**

In [44]:
x12 = np.zeros(5)

print(x12)

[0. 0. 0. 0. 0.]


In [45]:
# dtype can also be specified

x13 = np.zeros([2,2], dtype=int)

print(x13)

[[0 0]
 [0 0]]


**arange function


The arange function creates sequences of numbers. It is analogous to range that returns arrays instead of lists.**

In [46]:
# In the below example arranging can be happen by 10 is the start and 20 is the end point and 2 is the step function
x14 = np.arange(10, 20, 2)
x15 = x14.reshape(5,1)

print(x14)
print(x15)

[10 12 14 16 18]
[[10]
 [12]
 [14]
 [16]
 [18]]


In [47]:
# arange function with float arguments

x15 = np.arange(10, 20, 0.5)

print(x15)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]


*linspace function


It returns evenly spaced numbers over a specified interval. The endpoint of the interval can optionally be excluded :-**

In [48]:
# In the below linspace 2 is the start and 4 is the endn point and 6 is the totall no.of we want
x16 = np.linspace(2.0, 4.0, num=6)

print(x16)

[2.  2.4 2.8 3.2 3.6 4. ]


In [50]:
x17 = np.linspace(2, 4, num=20)

print(x17)

[2.         2.10526316 2.21052632 2.31578947 2.42105263 2.52631579
 2.63157895 2.73684211 2.84210526 2.94736842 3.05263158 3.15789474
 3.26315789 3.36842105 3.47368421 3.57894737 3.68421053 3.78947368
 3.89473684 4.        ]


*Numpy array from numerical ranges
In this section, I will discuss how to create an array from numerical ranges.


numpy.arange
This function returns an ndarray object containing evenly spaced values within a given range. 

The syntax 

numpy.arange(start, stop, step, dtype)**

In [ ]:
# create an array

y1 = np.arange(5) 

print(y1)

[0 1 2 3 4]


In [ ]:
# dtype set
np.arange(5, dtype = float)



array([0., 1., 2., 3., 4.])

*Adding or removing elements


resize - returns a new array with the specified shape


append - appends the values to the end of an array


insert - inserts the values along the given axis before the given indices


delete - returns a new array with sub-arrays along an axis deleted


unique - finds the unique elements of an array**

**Numpy slicing**

*
Basic slicing is an extension of Python's basic concept of slicing to n dimensions. 

A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of an array.**

In [ ]:
x18 = np.arange(10) 

print(x18)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
s = slice(2,5,2) 

print(x18[s])

[2 4]


The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object as follows:-



In [ ]:
x19 = x18[2:9:2]

print(x19)

[2 4 6 8]


In [ ]:
# slice single item 

x18 = np.arange(10) 

x20 = x18[5] 

print(x20)


5


In [ ]:
# slice items starting from index 

x18 = np.arange(10)

print(x18[2:])

[2 3 4 5 6 7 8 9]


In [ ]:
x20 = np.array([[1,2,3],[3,4,5],[4,5,6]])

print(x20) 

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [ ]:
x20.shape

(3, 3)

In [ ]:
# slice items starting from index
# in the below having 3(0,1,2) rows of data so it considering from 1 and 2
print(x20[1:])

**NumPy Arithmetic Operations**

In [ ]:
# create two arrays

z1 = np.array([10,20,30,40,50])

z2 = np.arange(5)

print(z1)

print(z2)

[10 20 30 40 50]
[0 1 2 3 4]


In [ ]:
# addition

z_add = z1 + z2

print(z_add)

[10 21 32 43 54]


In [ ]:
# subtraction

z_sub = z1 - z2

print(z_sub)

[10 19 28 37 46]


In [ ]:
# multiplication - elementwise product

z_mult = z1 * z2

print(z_mult)

[  0  20  60 120 200]


In [ ]:
# division

z_div = z1/2

print(z_div)

[ 5. 10. 15. 20. 25.]


In [ ]:
# comparision operator

z1 < 35

array([ True,  True,  True, False, False])

**numpy.reciprocal()
numpy.power()


numpy.mod()


numpy.real() 


numpy.imag() 


numpy.conj()


numpy.angle() **

**numpy.amin() and numpy.amax()**

**These functions return the minimum and the maximum from the elements in the given array along the specified axis.

For rows, axis = 1

For columns, axis = 0

In [52]:
i1 = np.array([[5,2,3],[1,5,6],[3,7,4]]) 

print(i1)

[[5 2 3]
 [1 5 6]
 [3 7 4]]


In [53]:
# In the three dimensional array it selects a min value from each 1 represents each row
print('Applying amin() function across rows:') 

print(np.amin(i1,1)) 

Applying amin() function across rows:
[2 1 3]


In [54]:
# In the three dimensional array it selects a min value from each o represents each column
print('Applying amin() function across columns:') 

print(np.amin(i1,0))

Applying amin() function across columns:
[1 2 3]


In [55]:
print('Applying amax() function across rows:') 

print(np.amax(i1,1)) 

Applying amax() function across rows:
[5 6 7]


In [56]:
print('Applying amax() function across columns:') 

print(np.amax(i1,0))

Applying amax() function across columns:
[5 7 6]


** numpy.percentile()


Percentile is a measure used in statistics indicating the value below 


which a given percentage of observations in a group of observations fall.**

In [59]:
# create an array
# after sorting  the values from low to high '50%' is nothing but median and 25 and 75 percentage values in that particular array
import numpy as np


i2 = np.array([[60,20,80],[30,40,90],[40,70,100]]) 

print(i2)

[[ 60  20  80]
 [ 30  40  90]
 [ 40  70 100]]


In [60]:
print('Applying percentile() function:')

print(np.percentile(i2,50))

Applying percentile() function:
60.0


In [61]:
print(np.percentile(i2,50,axis = 1))

[60. 40. 70.]


In [62]:
print(np.percentile(i2,50,axis = 0))

[40. 40. 90.]


*numpy.mean()


numpy.median()


numpy.average()


Variance

Standard Deviation
Standard deviation is the square root of the variance.


Variance is the average of squared deviations. It is given by mean(abs(x - x.mean())2)**.**

In [63]:
# declare an array
i4 = np.array([1,2,3,4]) 
print(np.var(i4))

1.25


numpy.sort()


The sort() function returns a sorted copy of the input array. It has the 


following parameters:−

numpy.sort(a, axis, kind, order)**

In [64]:
# declare an array
s1 = np.array([[9,4],[2,7]]) 

print('Our array is:')

print(s1)

Our array is:
[[9 4]
 [2 7]]


In [65]:
# sorting along rows, axis = 1

print('Applying sort() function along rows:')

print(np.sort(s1))

Applying sort() function along rows:
[[4 9]
 [2 7]]


In [66]:
# sorting along columns, axis = 0

print('Applying sort() function along columns:')

print(np.sort(s1, axis = 0))

Applying sort() function along columns:
[[2 4]
 [9 7]]


*numpy.argsort()
The argsort()

function performs an indirect sort on input array**

In [67]:
s2 = np.array([5,9,2]) 

print('Our array is:')

print(s2) 

Our array is:
[5 9 2]


In [74]:
s = np.array([2,5,7,4])

print('Our array is:')

print(s) 

Our array is:
[2 5 7 4]


In [75]:
np.argsort(s)

array([0, 3, 1, 2])

In [76]:
# applying argsort() to s2
# argsort is nothing but sorting the elements and writing thier index number

s3 = np.argsort(s2) 

print(s3)

[2 0 1]


In [77]:
# reconstruct original array in sorted order

print(s2[s3]) 

[2 5 9]


** NumPy Searching


NumPy package has a number of functions for searching inside an array. 


These functions enable us to find the maximum, the minimum as well as the elements satisfying a given condition.

numpy.argmax() and numpy.argmin()
These two functions return the indices of maximum and minimum elements 

respectively along the given axis.**

In [102]:
d1 = np.array([[30,40,70],
               [80,20,10],
               [50,30,60]]) 

print('Our array is:')

print(d1) 

Our array is:
[[30 40 70]
 [80 20 10]
 [50 30 60]]


In [103]:
d1 = np.where(d2 > 4) 

print(d3) 

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))


Argmax is an operation that finds the argument that gives the maximum value from a target function. 

Argmax is most commonly used in machine learning for finding the class with the largest predicted probability. 

Argmax can be implemented manually, although the argmax() NumPy function is preferred in practice.**

In [79]:
# applying argmax() function to d1
# argmax is nothing but max value index 

print(np.argmax(d1))

3


In [80]:
# index of maximum number in flattened array

print(d1.flatten())

[30 40 70 80 20 10 50 30 60]


In [81]:
# array containing indices of maximum along axis 0(columns)
# it calls index value of an each array

maxindex = np.argmax(d1, axis = 0)

print(maxindex)

[1 0 0]


In [83]:
# array containing indices of maximum along axis 1(rows)
# it calls index value of an each array


maxindex = np.argmax(d1, axis = 1) 

print(maxindex) 

[2 0 2]


In [84]:
# applying argmin() function to d1

minindex = np.argmin(d1)

print(minindex) 

5


In [85]:
# flattened array along axis 0

minindex = np.argmin(d1, axis = 0) 

print(minindex)

[0 1 1]


In [86]:
# flattened array along axis 1

minindex = np.argmin(d1, axis = 1)

print(minindex)

[0 2 1]


*numpy.where()


The where() function returns the indices of elements in an input array where the given condition is satisfied.**

In [87]:
d2 = np.arange(9).reshape(3, 3) 

print('Our array is:')

print(d2) 

Our array is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [99]:
# it represents the index of both rows and columns of greater or lesser no.
print('Indices of elements > 2')

d3 = np.where(d2 > 4) 

print(d3)  


Indices of elements > 2
(array([1, 2, 2, 2]), array([2, 0, 1, 2]))


*numpy.extract()

The extract() function returns the elements satisfying any condition.**

In [104]:
e1 = np.arange(9.).reshape(3, 3) 

print('Our array is:')

print(e1)  

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [109]:
 # define a condition 

condition = np.mod(e1,8) == 0 

In [110]:
# evaluate the condition

print('Element-wise value of condition')

print(condition)

Element-wise value of condition
[[ True False False]
 [False False False]
 [False False  True]]


In [111]:
# extract corresponding elements

print('Extract elements using condition')

print(np.extract(condition, e1))

Extract elements using condition
[0. 8.]


*View or Shallow Copy


NumPy has a view() method which is a new array object that looks at the same 

data of the original array. In this case, change in dimensions of the new array doesn't change dimensions of the original.**

In [124]:
# declare an array

x1 = np.arange(6).reshape(3,2) 

print(x1) 

[[0 1]
 [2 3]
 [4 5]]


In [138]:
# create view of x1

y1 = x1.view()

print(y1)

[[0 1]
 [2 3]
 [4 5]]


In [139]:
y1[0,0] = 100 

print('Modified array y1:')

print(y1)  

Modified array y1:
[[100   1]
 [  2   3]
 [  4   5]]


In [141]:
x1

array([[100,   1],
       [  2,   3],
       [  4,   5]])

In [126]:
y1 is x1

False

In [140]:
# check the shape of both the arrays

print('Shape of y1:') 
print(y1.shape)  
print('\n')
print('Shape of x1:') 
print(x1.shape)

Shape of y1:
(3, 2)


Shape of x1:
(3, 2)


In [119]:
# Change the shape of y1
# In shallow copy we observe below changing the shape in y1 is does ont effect to the shape of x1

y1.shape = 2,3 

print(y1)

[[0 1 2]
 [3 4 5]]


In [128]:
# check the shape of x1
# the shape of x1 is not changed by changing the shape of y1 
x1.shape

print(x1)

[[0 1]
 [2 3]
 [4 5]]


*Deep Copy


The copy() function creates a deep copy. It is a complete copy of the array and its data, and doesn't share with the original array.**

In [129]:
# declare an array

z1 = np.array([[10,10], [2,3], [4,5]]) 

print('Array z1 is:')

print(z1)  

Array z1 is:
[[10 10]
 [ 2  3]
 [ 4  5]]


In [130]:
# create a deep copy of z1

y1 = z1.copy()

print('Array y1 is:')

print(y1) 

Array y1 is:
[[10 10]
 [ 2  3]
 [ 4  5]]


In [131]:
# y1 does not share any memory of x1

print('Can we write y1 is z1')

print(y1 is z1)  

Can we write y1 is z1
False


In [134]:
# change the contents of y1

y1[0,0] = 100 

print('Modified array y1:')

print(y1)  

Modified array y1:
[[100  10]
 [  2   3]
 [  4   5]]


In [135]:
# z1 remains unchanged

print(z1)

[[10 10]
 [ 2  3]
 [ 4  5]]




load() and save() functions handle /numPy binary files (with npy extension).
loadtxt() and savetxt() functions handle normal text files.**

**Random sampling with NumPy*

*rand()
This function creates an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).**

In [136]:
np.random.rand(3,2)

array([[0.14777839, 0.04818988],
       [0.93740801, 0.40946324],
       [0.92336934, 0.43591921]])

In [156]:
np.random.rand(25)

array([0.80025557, 0.69859852, 0.44539434, 0.55145183, 0.50253754,
       0.78303271, 0.79220123, 0.43730619, 0.93751083, 0.92267706,
       0.3635038 , 0.56271688, 0.55865079, 0.84033809, 0.54678369,
       0.20867359, 0.11862307, 0.95502714, 0.66843637, 0.96901511,
       0.80968977, 0.38953056, 0.36302829, 0.25900199, 0.90352882])

*randn()


It returns a sample (or samples) from the "standard normal" distribution.**

In [153]:
np.random.randn()

-0.06720687095143174

*randint()


It returns random integers from low (inclusive) to high (exclusive).**

In [154]:
np.random.randint(10, size=(2,4))

array([[0, 7, 2, 6],
       [5, 0, 5, 1]])

*random()


It returns random floats in the half-open interval [0.0, 1.0)*

In [157]:
np.random.random_sample()

0.7318821650088633

*choice()


It generates a random sample from a given 1-D array.**

In [163]:
# generates a uniform random sample from np.arange(5) of size 3

np.random.choice(10, 20)

array([3, 6, 8, 4, 6, 5, 7, 4, 5, 1, 3, 0, 2, 0, 9, 9, 2, 7, 4, 8])